services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Bundles\User\:
        resource: '../../*'
        exclude: '../../{Entity,Repository}'

    Bundles\User\Controller\:
        resource: '../../Controller'
        public: true
        tags: [controller.service_arguments]
