services:
    kernel:
        class: App\Kernel
        synthetic: true

    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    controller_resolver:
        class: App\HttpKernel\ControllerResolver
        arguments: ["@service_container"]

    request_stack:
        class: Symfony\Component\HttpFoundation\RequestStack

    argument_resolver:
        class: Symfony\Component\HttpKernel\Controller\ArgumentResolver

    http_kernel:
        class: Symfony\Component\HttpKernel\HttpKernel
        arguments: ["@event_dispatcher", "@controller_resolver", "@request_stack", "@argument_resolver"]
