services:
    router:
        class: Symfony\Component\Routing\Router
        factory: [App\Routing\RouterFactory, factory]
        arguments: ["@kernel", "@request_stack", "%kernel.root_dir%", "%kernel.cache_dir%", "%kernel.debug%"]

    router_listener:
        class: App\Routing\RouterListener
        arguments: ["@router"]
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onRequest, priority: 32}
