services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../../*'

    # The application kernel.
    kernel:
        synthetic: true
        public: true
    Symfony\Component\HttpKernel\KernelInterface: '@kernel'

    Symfony\Component\EventDispatcher\EventDispatcher:
        public: true
    Symfony\Component\EventDispatcher\EventDispatcherInterface: '@Symfony\Component\EventDispatcher\EventDispatcher'

    Symfony\Component\HttpKernel\Controller\ContainerControllerResolver:
    Symfony\Component\HttpKernel\Controller\ControllerResolverInterface: '@Symfony\Component\HttpKernel\Controller\ContainerControllerResolver'

    Symfony\Component\HttpFoundation\RequestStack:
        public: true

    Symfony\Component\HttpKernel\Controller\ArgumentResolverInterface:
        factory: [App\Controller\ArgumentResolver\ArgumentResolverFactory, factory]
        arguments: ["@service_container"]

    Symfony\Component\HttpKernel\HttpKernel:
        public: true

    # The application routing system.
    Symfony\Component\Routing\RouterInterface:
        factory: [App\Routing\RouterFactory, factory]
        arguments:
            $rootDir: "%kernel.root_dir%"
            $cacheDir: "%kernel.cache_dir%"
            $debug: "%kernel.debug%"
        public: true

    App\Routing\RouterListener:
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onRequest, priority: 32}

    # The application templating system.
    Symfony\Component\Templating\EngineInterface:
        factory: [App\Templating\TemplatingEngineFactory, factory]
        arguments: ["%kernel.root_dir%"]
        public: true
