services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../../*'

    # The application kernel.
    kernel:
        synthetic: true
        public: true
    Symfony\Component\HttpKernel\KernelInterface: '@kernel'

    Symfony\Component\EventDispatcher\EventDispatcher:
        public: true
    Symfony\Component\EventDispatcher\EventDispatcherInterface: '@Symfony\Component\EventDispatcher\EventDispatcher'

    Symfony\Component\HttpKernel\Controller\ContainerControllerResolver:
    Symfony\Component\HttpKernel\Controller\ControllerResolverInterface: '@Symfony\Component\HttpKernel\Controller\ContainerControllerResolver'

    Symfony\Component\HttpFoundation\RequestStack:
        public: true

    Symfony\Component\HttpKernel\Controller\ArgumentResolverInterface:
        factory: [App\Controller\ArgumentResolver\ArgumentResolverFactory, factory]
        arguments: ["@service_container"]

    Symfony\Component\HttpKernel\HttpKernel:
        public: true

    # The application routing system.
    Symfony\Component\Routing\Router:
        factory: [App\Routing\RouterFactory, factory]
        arguments:
            $bundles: "%kernel.bundles_metadata%"
            $cacheDir: "%kernel.cache_dir%"
            $debug: "%kernel.debug%"
        public: true
    Symfony\Component\Routing\RouterInterface: '@Symfony\Component\Routing\Router'
    Symfony\Component\Routing\Matcher\RequestMatcherInterface: '@Symfony\Component\Routing\Router'

    App\Routing\RouterListener:
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onRequest, priority: 32}

    # The application templating system.
    Symfony\Component\Templating\EngineInterface:
        factory: [App\Templating\TemplatingEngineFactory, factory]
        arguments: ["%kernel.project_dir%"]
        public: true
