services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $env: '%kernel.environment%'
            $debug: '%kernel.debug%'
            $rootDir: '%kernel.root_dir%'
            $projectDir: '%kernel.project_dir%'
            $configDir: '%kernel.config_dir%'
            $cacheDir: '%kernel.cache_dir%'
            $logsDir: '%kernel.logs_dir%'
            $bundles: '%kernel.bundles%'
            $bundlesMetadata: '%kernel.bundles_metadata%'

    App\:
        resource: '../../*'

    # The application kernel.
    kernel:
        synthetic: true
    Symfony\Component\HttpKernel\KernelInterface: '@kernel'

    Symfony\Component\EventDispatcher\EventDispatcher: ~
    Symfony\Component\EventDispatcher\EventDispatcherInterface:
        alias: Symfony\Component\EventDispatcher\EventDispatcher

    Symfony\Component\HttpKernel\Controller\ContainerControllerResolver:
    Symfony\Component\HttpKernel\Controller\ControllerResolverInterface: '@Symfony\Component\HttpKernel\Controller\ContainerControllerResolver'

    Symfony\Component\HttpFoundation\RequestStack: ~

    Symfony\Component\HttpKernel\Controller\ArgumentResolverInterface:
        factory: [App\Controller\ArgumentResolver\ArgumentResolverFactory, factory]

    Symfony\Component\HttpKernel\HttpKernel:
        public: true

    # The application routing system.
    Symfony\Component\Routing\Router:
        factory: [App\Routing\RouterFactory, factory]
    Symfony\Component\Routing\RouterInterface: '@Symfony\Component\Routing\Router'
    Symfony\Component\Routing\Matcher\RequestMatcherInterface: '@Symfony\Component\Routing\Router'

    App\Routing\RouterListener:
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onRequest, priority: 32}

    # The application templating system.
    Symfony\Component\Templating\EngineInterface:
        factory: [App\Templating\TemplatingEngineFactory, factory]

    # Other utilities.
    Symfony\Component\Filesystem\Filesystem: ~
