services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Symfony\Component\Asset\PackageInterface:
        factory: [App\Assets\PackageFactory, factory]
        arguments: ['%assets.base_path%', '%assets.version_format%', '%assets.version%']
