services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Doctrine\ORM\EntityManagerInterface:
        factory: [App\Doctrine\EntityManagerFactory, factory]
        arguments:
            -
                driver: "%doctrine.driver%"
                host: "%doctrine.host%"
                port: "%doctrine.port%"
                user: "%doctrine.user%"
                password: "%doctrine.password%"
                dbname: "%doctrine.database%"
                charset: "%doctrine.charset%"
                defaultTableOptions:
                    charset: "%doctrine.charset%"
                    collate: "%doctrine.collate%"
            - "%kernel.environment%"
            - "%kernel.bundles_metadata%"
        public: true
