services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    doctrine:
        class: Doctrine\ORM\EntityManagerInterface
        factory: [App\Doctrine\EntityManagerFactory, factory]
        arguments:
            - "%doctrine.driver%"
            - "%doctrine.host%"
            - "%doctrine.port%"
            - "%doctrine.user%"
            - "%doctrine.password%"
            - "%doctrine.database%"
            - "%kernel.environment%"
            - "%kernel.bundles_metadata%"
        public: true
