services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $cacheDir: '%kernel.cache_dir%'

    App\:
        resource: '../../*'

    kernel:
        class: Symfony\Component\HttpKernel\KernelInterface
        synthetic: true
        public: true
    Symfony\Component\HttpKernel\KernelInterface: '@kernel'

    Psr\Container\ContainerInterface: '@service_container'

    Symfony\Component\EventDispatcher\EventDispatcher:
        public: true
    Symfony\Component\EventDispatcher\EventDispatcherInterface:
        alias: Symfony\Component\EventDispatcher\EventDispatcher
        public: true

    Symfony\Component\HttpKernel\Controller\ContainerControllerResolver:
    Symfony\Component\HttpKernel\Controller\ControllerResolverInterface: '@Symfony\Component\HttpKernel\Controller\ContainerControllerResolver'

    Symfony\Component\HttpFoundation\RequestStack: ~

    Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver:
        arguments: [~]
    Symfony\Component\HttpKernel\Controller\ArgumentResolverInterface:
        factory: [App\Controller\ArgumentResolver\ArgumentResolverFactory, factory]

    Symfony\Component\HttpKernel\HttpKernel:
        public: true
