services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../../*'

    App\Kernel:
        synthetic: true
        public: true

    Symfony\Component\EventDispatcher\EventDispatcher:
        public: true
    Symfony\Component\EventDispatcher\EventDispatcherInterface: '@Symfony\Component\EventDispatcher\EventDispatcher'

    Symfony\Component\HttpKernel\Controller\ControllerResolverInterface: '@App\HttpKernel\ControllerResolver'

    Symfony\Component\HttpFoundation\RequestStack:
        public: true

    Symfony\Component\HttpKernel\Controller\ArgumentResolver:
    Symfony\Component\HttpKernel\Controller\ArgumentResolverInterface: '@Symfony\Component\HttpKernel\Controller\ArgumentResolver'

    Symfony\Component\HttpKernel\HttpKernel:
        public: true
